version: '3.9'
services:
  api:
    build: ./Atmosphere.BE
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
      - 5001:5001
    depends_on: 
      - mongo_db
  mongo_db:
    image: mongo:5.0.8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=atmosphere
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  webapp:
    build: ./WebApp

volumes:
  mongodb:
  mongoconfig:
  exclude:
