/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthResponseDto {
    #[serde(rename = "token")]
    pub token: String,
}

impl AuthResponseDto {
    pub fn new(token: String) -> AuthResponseDto {
        AuthResponseDto {
            token,
        }
    }
}


