/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BaseUserDto {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "role")]
    pub role: crate::models::UserRole,
    #[serde(rename = "isActive")]
    pub is_active: bool,
}

impl BaseUserDto {
    pub fn new(id: uuid::Uuid, username: String, role: crate::models::UserRole, is_active: bool) -> BaseUserDto {
        BaseUserDto {
            id,
            username,
            role,
            is_active,
        }
    }
}


