/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmailConfiguration {
    #[serde(rename = "smtpServer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smtp_server: Option<Option<String>>,
    #[serde(rename = "smtpPort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smtp_port: Option<Option<i32>>,
    #[serde(rename = "smtpUsername", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smtp_username: Option<Option<String>>,
    #[serde(rename = "smtpPassword", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smtp_password: Option<Option<String>>,
    #[serde(rename = "emailAddress", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<Option<String>>,
    #[serde(rename = "serverEmailAddress", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server_email_address: Option<Option<String>>,
}

impl EmailConfiguration {
    pub fn new() -> EmailConfiguration {
        EmailConfiguration {
            smtp_server: None,
            smtp_port: None,
            smtp_username: None,
            smtp_password: None,
            email_address: None,
            server_email_address: None,
        }
    }
}


