/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetChartData {
    #[serde(rename = "deviceId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "startDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<Option<String>>,
    #[serde(rename = "endDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Option<String>>,
    #[serde(rename = "readingType")]
    pub reading_type: crate::models::ReadingType,
}

impl GetChartData {
    pub fn new(reading_type: crate::models::ReadingType) -> GetChartData {
        GetChartData {
            device_id: None,
            start_date: None,
            end_date: None,
            reading_type,
        }
    }
}


