/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationType {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "unknown")]
    Unknown,

}

impl ToString for NotificationType {
    fn to_string(&self) -> String {
        match self {
            Self::Email => String::from("email"),
            Self::Unknown => String::from("unknown"),
        }
    }
}

impl Default for NotificationType {
    fn default() -> NotificationType {
        Self::Email
    }
}




