/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotificationSettingsDto {
    #[serde(rename = "emailEnabled")]
    pub email_enabled: bool,
    #[serde(rename = "emailTo")]
    pub email_to: String,
    #[serde(rename = "temperatureThresholdMin")]
    pub temperature_threshold_min: f64,
    #[serde(rename = "temperatureThresholdMax")]
    pub temperature_threshold_max: f64,
}

impl NotificationSettingsDto {
    pub fn new(email_enabled: bool, email_to: String, temperature_threshold_min: f64, temperature_threshold_max: f64) -> NotificationSettingsDto {
        NotificationSettingsDto {
            email_enabled,
            email_to,
            temperature_threshold_min,
            temperature_threshold_max,
        }
    }
}


