/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReadingDto {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "device")]
    pub device: Box<crate::models::DeviceDto>,
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "unit")]
    pub unit: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::ReadingType,
}

impl ReadingDto {
    pub fn new(id: uuid::Uuid, device: crate::models::DeviceDto, value: f64, unit: String, timestamp: String, r#type: crate::models::ReadingType) -> ReadingDto {
        ReadingDto {
            id,
            device: Box::new(device),
            value,
            unit,
            timestamp,
            r#type,
        }
    }
}


