/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReadingType {
    #[serde(rename = "temperature")]
    Temperature,
    #[serde(rename = "humidity")]
    Humidity,
    #[serde(rename = "pressure")]
    Pressure,
    #[serde(rename = "unknown")]
    Unknown,

}

impl ToString for ReadingType {
    fn to_string(&self) -> String {
        match self {
            Self::Temperature => String::from("temperature"),
            Self::Humidity => String::from("humidity"),
            Self::Pressure => String::from("pressure"),
            Self::Unknown => String::from("unknown"),
        }
    }
}

impl Default for ReadingType {
    fn default() -> ReadingType {
        Self::Temperature
    }
}




