/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReadingDtoPagedList {
    #[serde(rename = "currentPage")]
    pub current_page: i32,
    #[serde(rename = "totalPages")]
    pub total_pages: i32,
    #[serde(rename = "pageSize")]
    pub page_size: i32,
    #[serde(rename = "totalCount")]
    pub total_count: i32,
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ReadingDto>,
    #[serde(rename = "hasPrevious")]
    pub has_previous: bool,
    #[serde(rename = "hasNext")]
    pub has_next: bool,
}

impl ReadingDtoPagedList {
    pub fn new(current_page: i32, total_pages: i32, page_size: i32, total_count: i32, items: Vec<crate::models::ReadingDto>, has_previous: bool, has_next: bool) -> ReadingDtoPagedList {
        ReadingDtoPagedList {
            current_page,
            total_pages,
            page_size,
            total_count,
            items,
            has_previous,
            has_next,
        }
    }
}


