/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReadingDto {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "deviceId")]
    pub device_id: uuid::Uuid,
    #[serde(rename = "sensorIdentifier")]
    pub sensor_identifier: String,
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::ReadingType,
}

impl ReadingDto {
    pub fn new(id: uuid::Uuid, device_id: uuid::Uuid, sensor_identifier: String, value: f64, timestamp: String, r#type: crate::models::ReadingType) -> ReadingDto {
        ReadingDto {
            id,
            device_id,
            sensor_identifier,
            value,
            timestamp,
            r#type,
        }
    }
}


