/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RegisterDevice {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl RegisterDevice {
    pub fn new(username: String, identifier: String, password: String) -> RegisterDevice {
        RegisterDevice {
            username,
            identifier,
            password,
        }
    }
}


