/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Severity {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,

}

impl ToString for Severity {
    fn to_string(&self) -> String {
        match self {
            Self::Info => String::from("info"),
            Self::Warning => String::from("warning"),
            Self::Error => String::from("error"),
        }
    }
}

impl Default for Severity {
    fn default() -> Severity {
        Self::Info
    }
}




