/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateValidationRules {
    #[serde(rename = "readingType")]
    pub reading_type: crate::models::ReadingType,
    #[serde(rename = "rules")]
    pub rules: Vec<crate::models::ValidationRuleDto>,
    #[serde(rename = "deviceId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<Option<uuid::Uuid>>,
}

impl UpdateValidationRules {
    pub fn new(reading_type: crate::models::ReadingType, rules: Vec<crate::models::ValidationRuleDto>) -> UpdateValidationRules {
        UpdateValidationRules {
            reading_type,
            rules,
            device_id: None,
        }
    }
}


