/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateValidationRules {
    #[serde(rename = "readingType")]
    pub reading_type: crate::models::ReadingType,
    #[serde(rename = "rules")]
    pub rules: Vec<crate::models::ValidationRuleDto>,
}

impl UpdateValidationRules {
    pub fn new(reading_type: crate::models::ReadingType, rules: Vec<crate::models::ValidationRuleDto>) -> UpdateValidationRules {
        UpdateValidationRules {
            reading_type,
            rules,
        }
    }
}


