/*
 * Atmosphere API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidationRuleDto {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "condition")]
    pub condition: String,
    #[serde(rename = "severity")]
    pub severity: crate::models::Severity,
}

impl ValidationRuleDto {
    pub fn new(message: String, condition: String, severity: crate::models::Severity) -> ValidationRuleDto {
        ValidationRuleDto {
            message,
            condition,
            severity,
        }
    }
}


